### ISSUE TITLE
input requires prompt?

### ISSUE THREAD

**Issue by brianpmarks** [trinketapp/skulpt#14]
@albertjan Should input require a prompt? We had this reported by a user. Here's an example: https://trinket.io/python/3861f3bed7

**Comment by albertjan** [comment]
it shouldn't

**Comment by waywaaard** [comment]
Error should be in https://github.com/trinketapp/skulpt/blob/master/src/builtin.js#L810

**Comment by brianpmarks** [comment]
Fixed by #15.
